apiVersion: v1
kind: Secret
metadata:
  name: lavagna-mysql-secrets
  namespace: app1
  labels: 
    name: lavagna
type: Opaque
stringData:

  datasource_dialect: 'MYSQL'
  datasource_url: 'jdbc:mysql://mysql-service:3306/lavagna'
  datasource_username: 'solid_snake'
  datasource_password: 'metalgear'
  profiles_active: 'prod'

  MYSQL_ROOT_PASSWORD: 'strangelove'
  MYSQL_USER: 'solid_snake'
  MYSQL_PASSWORD: 'metalgear'
  MYSQL_DATABASE: 'lavagna'





